# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
