# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20161024_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='series',
            field=models.CharField(max_length=200),
        ),
    ]
