# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20161024_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
