# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comics', '0004_comic_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistpeople', to='comics.People'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='letterer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettererpeople', to='comics.People'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writerpeople', to='comics.People'),
        ),
        migrations.AddField(
            model_name='usercomics',
            name='comic_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomic', to='comics.Comic'),
        ),
        migrations.AddField(
            model_name='usercomics',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
