# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_auto_20161030_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComics',
            new_name='UserComic',
        ),
    ]
