# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_auto_20161030_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomic',
            old_name='user_id',
            new_name='user',
        ),
    ]
