# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_auto_20161031_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='notes',
        ),
    ]
